/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Answer019 */

#ifndef _Included_Answer019
#define _Included_Answer019
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Answer019
 * Method:    randomNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Answer019_randomNum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
